global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - follow_redirects: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: []
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - localhost:9090
  - job_name: simple-api-job
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - 192.168.1.73:8080
        labels:
            application: simple-api
